on:
  push:
    branches:
    - master
name: Push Event
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}
      run: |
        SHA="${GITHUB_SHA:0:7}"
        V="$GITHUB_RUN_NUMBER-$SHA"
        echo "$V" > VERSION
        echo "$DOCKERHUB" | docker login --username musabmasood --password-stdin
        docker build . -t "musabmasood/gitops-myapp:1.$V" && docker push "musabmasood/gitops-myapp:1.$V"
