on:
  push:
    branches:
    - "**"
name: Push Event
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "$GITHUB_RUN_NUMBER" > VERSION
    - run: echo "$DOCKERHUB" | docker login --username musabmasood --password-stdin
    - run: docker build . -t "musabmasood/gitops-myapp:1.$GITHUB_RUN_NUMBER" && docker push "musabmasood/gitops-myapp:1.$GITHUB_RUN_NUMBER"
      
