on:
  push:
    branches:
    - master
name: Push Event
env:
  IMAGE_VERSION: "$GITHUB_RUN_NUMBER-${GITHUB_SHA:0:7}"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}
      run: |
        echo "$IMAGE_VERSION" > VERSION
        echo "$DOCKERHUB" | docker login --username musabmasood --password-stdin
        docker build . -t "musabmasood/gitops-myapp:1.$IMAGE_VERSION" && docker push "musabmasood/gitops-myapp:1.$IMAGE_VERSION"
