on:
  push:
    branches:
#     - "*" # uncomment when testing on branch
    - master
name: Build and push
jobs:
  build-and-push-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}
      run: |
        SHA="${GITHUB_SHA:0:7}"
        V="1.${GITHUB_RUN_NUMBER}-$SHA"
        echo "$V" > VERSION
        echo "$DOCKERHUB" | docker login --username musabmasood --password-stdin
        docker build . -t "musabmasood/gitops-myapp:1.$V" && docker push "musabmasood/gitops-myapp:1.$V"
  # ideally update chart should be in a script
  update-chart:
    name: Update version in helm chart
    runs-on: ubuntu-latest
    needs: [build-and-push-image]
    steps:
    - uses: actions/checkout@v2
      with:
        repository: musabmasood/gitops-myproject-k8s
        path: gitops-myproject-k8s
        ssh-key: ${{ secrets.GITOPS_DEPLOY_KEY }}
    - run: |
        SHA="${GITHUB_SHA:0:7}"
        V="1.${GITHUB_RUN_NUMBER}-$SHA"
        
        git config --global user.name "gitops-myapp-ci"
        git config --global user.email gitops-myapp-ci@github.com
        cd gitops-myproject-k8s/charts/helm-myapp
        
        # update appVersion in Chart.yaml
        sed -i "s/appVersion.*/appVersion: $V/g" Chart.yaml
        
        # update image tag for the chart
        sed -i "s/tag.*/tag: $V/g" values.yaml
        
        git add Chart.yaml values.yaml
        git commit -m 'bump version'
        git push
