on:
  push:
    branches:
    - "*" # uncomment when testing on branch
    # - master
name: Push Event
jobs:
  build-and-push-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}
      run: |
        SHA="${GITHUB_SHA:0:7}"
        V="${GITHUB_RUN_NUMBER}-$SHA"
        echo "$V" > VERSION
        echo "$DOCKERHUB" | docker login --username musabmasood --password-stdin
        docker build . -t "musabmasood/gitops-myapp:1.$V" && docker push "musabmasood/gitops-myapp:1.$V"
  update-chart:
    name: Update version in helm chart
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: musabmasood/gitops-myproject-k8s
        path: gitops-myproject-k8s
    - run: |
        SHA="${GITHUB_SHA:0:7}"
        V="${GITHUB_RUN_NUMBER}-$SHA"
        
        cd charts/helm-myapp
        
        # update appVersion in Chart.yaml
        sed -i "s/appVersion.*/appVersion: $V/g" Chart.yaml
        
        # update image tag for the chart
        sed -i "s/tag.*/tag: $V/g" values.yaml
      
        cat Chart.yaml
        cat values.yaml
        
        git add Chart.yaml values.yaml
        git commit -m 'bump version'
        git status
        git push
